# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hilocal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
